### ISSUE TITLE
links in plugin output should stay underlined

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1290]
**Is your feature request related to a problem? Please describe.**
The CSS currently styles all links to be not decorated. For the UI of Thruk itself this makes perfect sense. But if a nagios plugin output contains links, these should still be decorated with the typical underline, else users will mistake the links for plain text.

**Describe the solution you'd like**
```css
.col_plugin_output a,
.detail_plugin_output a {
    text-decoration: underline;
}
```

**Describe alternatives you've considered**
Any other highlight would also work, since one might argue that clicking the link might be confusable with showing the long plugin output.
